# Generated by Django 6.0.2 on 2026-02-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('structure_result', models.CharField(choices=[('CityLocation', 'CityLocation'), ('GenericModel', 'GenericModel'), ('BaseModel', 'BaseModel'), ('FinalRequestOptions', 'FinalRequestOptions'), ('_AzureContentFilterResultDetail', '_AzureContentFilterResultDetail'), ('_AzureContentFilterResult', '_AzureContentFilterResult'), ('_AzureInnerError', '_AzureInnerError'), ('_AzureError', '_AzureError'), ('_AzureErrorResponse', '_AzureErrorResponse')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='handler.aimodel')),
            ],
        ),
    ]
