# Generated by Django 6.0.2 on 2026-02-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_mcpserver_alter_prompt_structure_result_prompt_mcps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcpserver',
            options={'verbose_name': 'MCP Server', 'verbose_name_plural': 'MCP Servers'},
        ),
        migrations.AlterUniqueTogether(
            name='mcpserver',
            unique_together={('name', 'path')},
        ),
    ]
