# Generated by Django 6.0.2 on 2026-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_alter_prompt_structure_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='family',
            field=models.CharField(default='ollama', max_length=50),
        ),
    ]
