# Generated by Django 6.0.2 on 2026-02-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0007_aimodel_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField()),
                ('usage', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='handler.prompt')),
            ],
        ),
    ]
